output "cluster_id" {
    description = "EKS Cluster Id"
    value = module.eks.cluster_id
}

output "cluster_endpoint" {
    description = "Endpoint for EKS control plane"
    value = module.eks.cluster_endpoint
}

output "kubectl_config" {
    description = "kubectl config as generated by the module"
    value = module.eks.kubeconfig
}

output "config_map_aws_auth" {
    description = "kubenertes configuration to authenticate to cluster control plane"
    value = module.eks.config_map_aws_auth
}

output "region" {
    description = "AWS region"
    value = var.region
}

output "cluster_name" {
    description = "Kubernetes Cluster name"
    value = local.cluster_name
}